name:                hitcounter
version:             0.1.0.0
license:             BSD3
author:              "Sergio de Carvalho"
copyright:           "2018 Sergio de Carvalho"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README.md

dependencies:
- base >= 4.7 && < 5

executables:
  hitcounter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - text
    - transformers
    - scotty
